export const CommonAction = {
    GET_DATA: 'GET_DATA',
    GET_DATA_SUCCESS: "GET_DATA_SUCCESS",
    GET_DATA_FAIL: "GET_DATA_FAIL",
    GET_MORE_DATA_SUCCESS: "GET_MORE_DATA_SUCCESS",
    GET_MORE_DATA_FAIL: "GET_MORE_DATA_FAIL",
    TRIGGER_LOADING: 'TRIGGER_LOADING',
    TRIGGER_LOADINGMORE: 'TRIGGER_LOADINGMORE',
    UPDATE_PAGINATION_LINKS: 'UPDATE_PAGINATION_LINKS',
    TRIGGER_SHOW: 'TRIGGER_SHOW',
    UPDATE_VALUE: "UPDATE_VALUE",
    APPOINT_ELEMENT: "APPOINT_ELEMENT",
    GET_DATA_RETURN_NULL: "GET_DATA_RETURN_NULL",
    LOGGER_ACTION: "LOGGER_ACTION",
}

export const CommonActionId = {
    GET_POPULAR_DATA: 'GET_POPULAR_DATA',
    GET_SEARCH_DATA: 'GET_SEARCH_DATA',
    GET_TRENDING_DATA: 'GET_TRENDING_DATA',
    UPDATE_TRENDING_LANGUAGE: "UPDATE_TRENDING_LANGUAGE",
    UPDATE_TRENDING_SINCE: "UPDATE_TRENDING_SINCE",
    REFRESH_TRENDING_DATA: "REFRESH_TRENDING_DATA",
    APPOINT_TRENDING_FLATLIST: "APPOINT_TRENDING_FLATLIST",
    GET_ALL_LANGUAGE: "GET_ALL_LANGUAGE",
    GET_REPOSITORY_INFO_DATA: "GET_REPOSITORY_INFO_DATA",
}
